### ISSUE TITLE
theta_deg hardcoded in plot_effective_area

### ISSUE THREAD

**Issue by jebuss** [fact-project/fact_plots#14]
When using the e.g. the disp_regression method from classifier_tools, the feature `theta_deg` is removed. In this case the plot_effective_area script would not work, since `theta_deg` is missing. 

Accordingly one needs to be able to choose a different variable name instead.

see also: https://github.com/fact-project/classifier-tools/issues/41

**Comment by maxnoe** [comment]
No. One does not need to use a different variable name. The feature is not present. it can be calculated using `fact_calc_theta` from pyfact
